name: Trigger lighthouse
on:
  workflow_dispatch:
  release:
   type: ['create']

jobs:
  generatePerfReport:
    runs-on: ubuntu-latest

    # defaults:
    #   run:
    #     working-directory: e2e/perf

    strategy:
      matrix:
        node-version: [20.17]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install node ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies for Chrome
      run: sudo apt-get install -y libnss3 libatk-bridge2.0-0 libx11-xcb1 libxcomposite1 libxcursor1 libxdamage1 libxi6 libxtst6 libgconf-2-4 libgbm-dev libasound2 libpangocairo-1.0-0 libgtk-3-0 libxrandr2
    
    - name: Install lighthouse
      run: npm install -g lighthouse  # Install Lighthouse globally

    - name: Install puppeteer
      run: npm install -g puppeteer  # Install Lighthouse globally

    - name: Install Light house puppeteer
      run: npm install -g puppeteer  # Install Lighthouse globally

    - name: Trigger the script
      run: node hack.mjs ${{ github.run_number }}

    # - name: Upload Lighthouse report
    #   uses: actions/upload-artifact@v4  # Upload the report as an artifact
    #   with:
    #     name: lighthouse-report
    #     path: ./result/Case.html

    - name: Configure Git
      run: |
          git config user.name "Shriram Gokhale"
          git config user.email "shriramgokhale.m@planview.com"
          git remote set-url origin https://shriramgokhale.m:${{ secrets.PAT_TOKEN }}@github.com/shriramgokhalem/Hackathon.git
    
    - name: Create Folder with Run Number
      run: |
          folder_name="${{ github.run_number }}"
          echo "Creating folder: $folder_name"
          cd result
          mkdir -p $folder_name
          echo "Folder created: $folder_name"

          echo "This is a file in the new folder" > $folder_name/info.txt

    - name: Commit and push changes folder
      uses: EndBug/add-and-commit@v9
      with:
          author_name: Shriram Gokhale
          author_email: shriramgokhale.m@planview.com
          message: 'Create new folder and add file'
          add: './result/${{ github.run_number }}/'
    
    - name: Commit and push changes
      uses: EndBug/add-and-commit@v9
      with:
          author_name: Shriram Gokhale
          author_email: shriramgokhale.m@planview.com
          message: 'Add generated file'
          add: "./result/${{ github.run_number }}/Case.html"
