name: Trigger lighthouse
on:
  workflow_dispatch:
  release:
   type: ['create']

jobs:
  generatePerfReport:
    runs-on: ubuntu-latest

    # defaults:
    #   run:
    #     working-directory: e2e/perf

    strategy:
      matrix:
        node-version: [20.17]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install node ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies for Chrome
      run: sudo apt-get install -y libnss3 libatk-bridge2.0-0 libx11-xcb1 libxcomposite1 libxcursor1 libxdamage1 libxi6 libxtst6 libgconf-2-4 libgbm-dev libasound2 libpangocairo-1.0-0 libgtk-3-0 libxrandr2
    
    - name: Install lighthouse
      run: npm install -g lighthouse  # Install Lighthouse globally

    - name: Install puppeteer
      run: npm install -g puppeteer  # Install Lighthouse globally

    - name: Install Light house puppeteer
      run: npm install -g puppeteer  # Install Lighthouse globally

    - name: Trigger the script
      run: node hack.mjs

    - name: Upload Lighthouse report
      uses: actions/upload-artifact@v2  # Upload the report as an artifact
      with:
        name: lighthouse-report
        path: ./result/case.html
